version: '3.7'

services:
  graphql:
    build:
      context: ./graphql
    ports:
      - 3000:3000
    container_name: graphql
    environment:
      PORT: 3000
    volumes:
      - ./graphql:/workdir
      - ./graphql/node_modules:/workdir/node_modules

  digimon-api:
    build:
      context: stardew-valley-api
    ports:
      - 3001:3001
    container_name: stardew-valley-api
    environment:
      PORT: 3001
    volumes:
      - ./digimon-api:/workdir
      - ./digimon-api/node_modules:/workdir/node_modules